### PR TITLE
Implement CI Testing with Saucelabs

### PR DESCRIPTION
**Pull request by evilaliv3**
This pull request implement support for testing scrypt-async-js in the cloud among multiple user browsers by means of SauceLabs.com.

@dchest: this cloud service is free for opensource projects and would be valuable to add it for scrpt-async so to properly validate the implementation against browsers setups.

Image used in the badge: https://saucelabs.com/browser-matrix/evilaliv3.svg
Readme.md badge viewable at: https://github.com/evilaliv3/scrypt-async-js/tree/feature/saucelabs

p.s. i've also removed the grunt-string-replace library that i included wrongly in previowu pull request

### CODE REVIEW

**Comment by dchest** [comment]
Awesome, thanks! Do you think this can be fixed: https://travis-ci.org/dchest/scrypt-async-js/jobs/61231467#L326 ? Is this a timeout?

**Comment by evilaliv3** [comment]
the internal code is the following:

            if (attempts === 0) {
              var errorMessage = "After trying " + me.statusCheckAttempts +
                                 " times with a delay of " + me.pollInterval +
                                 "s, this job never reached 'complete' status.";
              throw new Error(errorMessage);
            } else {
              return Q
                .delay(me.pollInterval)
                .then(fetch.bind(this, retries));
            }


so if i'm not wrong reading from https://github.com/axemclion/grunt-saucelabs the relevant wariables should be:

    pollInterval: Number of milliseconds between each retry to see if a test is completed or not (default: 2000). Optional

    statusCheckAttempts: Number of times to attempt to see if a test is completed or not (default: 90). Effectively, your tests have statusCheckAttempts * pollInterval seconds to complete (Thus, 180s by default). Set to -1 to try foreve

**Comment by dchest** [comment]
@evilaliv3 will you set it or should I try?

**Comment by evilaliv3** [comment]
ah! you were waiting for me!

sorry let me do it now.

**Comment by dchest** [comment]
No hurry, I wasn't actually waiting for anything, was just busy with other things :-) Would be good if the CI build passes before I merge.

**Comment by evilaliv3** [comment]
Ok @dchest i finally succeded.
i removed the specific test you put against node 0.10, 0.12 and iojs and i simply written "stable".
iojs was having issues to run the instrumented code. eventually we should differentiate but i think that now that we have real browser tests it is not required that we test against node as the libray is thought for the browsers.

**Comment by dchest** [comment]
Yay, thank you!

**Pull request merged**
