### PR TITLE
Feature/webworker

### PR DESCRIPTION
**Pull request by evilaliv3**
@dchest this pull request:
- implement a minimalistic web worker for scrypt-async-js;
- refactor minification of the library by means of Grunt instead of manual scripts;
- implement minification for web worker addition;
- refactor unit tests of the library by means of Grunt + Mocha;
- implement code coverage tracking by means of Istanbul + Coveralls (https://coveralls.io/); code coverage is now tracked on commit https://coveralls.io/r/evilaliv3/scrypt-async-js?branch=feature%2Fwebworker;
- add unit tests for Base64 encoding raising the code coverage from 87% up to 94%.

### CODE REVIEW

**Comment by dchest** [comment]
Could you please send WebWorker implementation in a separate PR from testing/build changes? I think we can improve it with some changes in scrypt itself, but I'd like to merge those other changes first.

Also, I've created a coveralls.io account, could you change the badge URL to ../dchest/..?

Thank you!

**Comment by dchest** [comment]
Nevermind, I'll cherry-pick commits.

**Comment by dchest** [comment]
BTW, I think there are services where you can test projects in different browsers/browser versions. Are you aware of of any, and if we can get our tests running there?

**Comment by dchest** [comment]
Merge some of the commits: https://github.com/dchest/scrypt-async-js/pull/10

**Comment by dchest** [comment]
Thanks for coverage stuff, by trying to achieve 100%, I discovered this bug in UTF8 encoding: https://github.com/dchest/scrypt-async-js/commit/c554347b36718cf51164a6d1449496a8cb646c35

**Comment by evilaliv3** [comment]
great :)

what do you htink about the webworker?

**Comment by evilaliv3** [comment]
closing the pull requests as the code has been manually integrated by @dchest

**Pull request closed without merging**
