### PR TITLE
Changes to Sauce Labs

### PR DESCRIPTION
**Pull request by dchest**

### CODE REVIEW

**Comment by dchest** [comment]
@evilaliv3 what did you do to fix "403 Forbidden" error for badge (https://saucelabs.com/browser-matrix/evilaliv3.svg)? It giving the error when I was not logged in, but then it worked. I have now the same problem: https://saucelabs.com/browser-matrix/dchest.svg. Maybe it just needs time? :)

**Comment by evilaliv3** [comment]
IT WORKS!

screenshot from 2015-05-07 11 58 30

**Comment by dchest** [comment]
Yes, your badge works, but mine gives 403 (when I'm not logged in)
screen shot 2015-05-07 at 14 04 35

I noticed the same with your badge first yesterday, but then it worked :)

**Comment by evilaliv3** [comment]
in relation to the svg, accessing directly now works without problems: https://saucelabs.com/browser-matrix/dchest.svg

the problems seems to lies in the emage cached by github CDN while showing badges. it seems that saucelabs does not use HTTP Caching headers correctly so that github reload the image online after a big refresh timeout.  it happened to me also yesterday as you noticed.

**Comment by evilaliv3** [comment]
in addition if you want you can protect the saucelabs token this way: https://docs.saucelabs.com/ci-integrations/travis-ci/

i dont't find it so relevant as i think nobody will abuse your free saucelabs account but who knows :)

**Comment by evilaliv3** [comment]
you find how i did here: https://github.com/globaleaks/GlobaLeaks/commit/4613b8c94cc698dac55dd6072a77217025288e07

**Comment by evilaliv3** [comment]
@dchest probablly this pull can be closed?

**Comment by dchest** [comment]
Waiting for CI to finish and merging. Thanks for your help!

**Comment by evilaliv3** [comment]
glad to help

i'm really interested in a patch that in case the interrupt step is set to -1 will skip totally to use the SetTimeout as i found that using a value like 1000000 is totally different from skipping it all due to the overhead introduced and the context change. are you still working on it? if now i will do today.

**Comment by dchest** [comment]
Yes, I wanted to do it today.

**Comment by evilaliv3** [comment]
@dchest i would suggest a little edit: https://github.com/globaleaks/GlobaLeaks/blob/devel/scripts/travis_saucelabs.sh
here you find the configurations that are interesting for current saucelabs support.
i've added: opera, android, iphone, ipad

here you have a demo: https://saucelabs.com/u/globaleaks

**Comment by evilaliv3** [comment]
here you can read about the browsers/platforms available: https://docs.saucelabs.com/reference/platforms-configurator/

give it a look an let me know that if there is something more that you would find useful

**Comment by dchest** [comment]
Having Opera is pretty useless, as they are on Chromium now, but having Android and iPad would be good. Thanks, I'll add them.

**Comment by evilaliv3** [comment]
i've updated the list: https://github.com/globaleaks/GlobaLeaks/blob/536435c60ad4ccb47d60094a556852ed9c9a499f/scripts/travis_saucelabs.sh

as starting point fo GlobaLeaks each browser on it's main OS we are running a test of any version.
e.g. firefox is tested one for the stable version on linux, but all version on Windows
e.g. chrome is tested one for the stable version on linux, but all version on Windows

we will run this for some days until we will recognize some of the differences/errors and when we will have a clear idea of the differences we will make  a reduction to the relevant versions.

i will put an update here.

\cc @fpietrosanti

**Pull request merged**
