### PR TITLE
Make use of JS Promises

### PR DESCRIPTION
**Pull request by Max13**
At first: The least invasive changes. No indentation to make the "commit" readable.
Secondly: Indentation cleanup.

Also, redondants tests are removed.

### CODE REVIEW

**Comment by dchest** [comment]
Sorry, this package was intended to be compatible even with the old IE versions, which us why it only uses typed arrays if it can detect their presence, otherwise it uses normal arrays. Promises are definitely a no-go for this, plus it's changing stable API for no reason.

**Comment by Max13** [comment]
No problem, by chance, it's my needs so I will keep it forked. What about a helper? Would you accept a helper (pscrypt) which returns a Promise and doesn't touch the current API ?

**Comment by dchest** [comment]
It's just a few lines of code to convert this to Promise, so I don't think any helpers are required. (BTW, I'm working on a modern scrypt for JS as part of an open source cryptographic library, and it will use promises.)

**Comment by Max13** [comment]
Fair enough. I’m waiting for your new implementation, I’m using this for now. Thx

**Pull request closed without merging**
